name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          apt install -y screen 
          screen python3 fuck.py
          screen python3 fuck.py
          screen python3 fuck.py
